name: Docker build
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_REPO: "rnestler/archlinux-rust"
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: ./build.sh beta nightly stable
